{% set name = "Pmw" %}
{% set version = "2.0.1" %}
{% set sha256 = "0b9d28f52755a7a081b44591c3dd912054f896e56c9a627db4dd228306ad1120" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    # https://sourceforge.net/p/pmw/patches/7/
    - Pmw_2_0_1-py36.patch

build:
  number: 1005
  script: python setup.py install --record record.txt

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - Pmw

about:
  home: http://pmw.sourceforge.net/
  license: MIT
  license_family: MIT
  license_file: Pmw/Pmw_2_0_1/doc/copyright.html
  summary: 'Toolkit for building high-level compound widgets in Python using the Tkinter module.'
  doc_url: http://pmw.sourceforge.net/doc/index.html
  dev_url: http://sourceforge.net/projects/pmw/

extra:
  recipe-maintainers:
    - mcs07
